"""Adiciona manager_id na tabela User

Revision ID: 166fcc0a6c2a
Revises: 0e8ecd3a644a
Create Date: 2025-10-15 11:27:29.247384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166fcc0a6c2a'
down_revision = '0e8ecd3a644a'
branch_labels = None
depends_on = None


# CÓDIGO CORRIGIDO - Use este.

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        # Substituímos 'None' por um nome único para a constraint.
        batch_op.create_foreign_key('fk_user_manager_id', 'user', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Usamos o mesmo nome que definimos acima para poder remover.
        batch_op.drop_constraint('fk_user_manager_id', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###


    # ### end Alembic commands ###
