"""Adiciona tabelas EventType e EventLog

Revision ID: 3c843439ed7a
Revises: 5ff7e2d59844
Create Date: 2025-11-12 18:33:22.870567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c843439ed7a'
down_revision = '5ff7e2d59844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_owner_id'))
        batch_op.drop_index(batch_op.f('ix_card_status'))

    with op.batch_alter_table('comportamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comportamento_categoria'))
        batch_op.drop_index(batch_op.f('ix_comportamento_created_at'))
        batch_op.drop_index(batch_op.f('ix_comportamento_titulo'))

    with op.batch_alter_table('discord_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_ticket_created_at'))
        batch_op.drop_index(batch_op.f('ix_discord_ticket_status'))

    with op.batch_alter_table('duvida', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guia_created_at'))
        batch_op.drop_index(batch_op.f('ix_guia_titulo'))

    with op.batch_alter_table('query_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_request_created_at'))
        batch_op.drop_index(batch_op.f('ix_query_request_status'))

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_reminder_datetime'))
        batch_op.drop_index(batch_op.f('ix_reminder_user_id'))

    with op.batch_alter_table('service_time', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_time_date_recorded'))
        batch_op.drop_index(batch_op.f('ix_service_time_user_id'))

    with op.batch_alter_table('ticket_follow_up', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_follow_up_user_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    with op.batch_alter_table('ticket_follow_up', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_follow_up_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('service_time', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_time_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_time_date_recorded'), ['date_recorded'], unique=False)

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_reminder_datetime'), ['reminder_datetime'], unique=False)

    with op.batch_alter_table('query_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_request_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guia_titulo'), ['titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_guia_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('duvida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('discord_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_discord_ticket_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('comportamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comportamento_titulo'), ['titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_comportamento_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comportamento_categoria'), ['categoria'], unique=False)

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_timestamp'))

    op.drop_table('event_log')
    op.drop_table('event_type')
    # ### end Alembic commands ###
