"""Adiciona campo ramal ao User

Revision ID: 4218c45d4b02
Revises: df19b48e1988
Create Date: 2025-11-18 00:10:09.519623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4218c45d4b02'
down_revision = 'df19b48e1988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ramal', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ramal')

    # ### end Alembic commands ###
