"""Adiciona image_filename a tabela Duvida

Revision ID: 5ff7e2d59844
Revises: 8d9fa258f186
Create Date: 2025-10-31 12:27:59.207973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff7e2d59844'
down_revision = '8d9fa258f186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comportamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comportamento_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_comportamento_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comportamento_titulo'), ['titulo'], unique=False)

    with op.batch_alter_table('discord_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_ticket_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discord_ticket_status'), ['status'], unique=False)

    with op.batch_alter_table('duvida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guia_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guia_titulo'), ['titulo'], unique=False)

    with op.batch_alter_table('query_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_request_status'), ['status'], unique=False)

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_reminder_datetime'), ['reminder_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('service_time', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_time_date_recorded'), ['date_recorded'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_time_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ticket_follow_up', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_follow_up_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('ticket_follow_up', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_follow_up_user_id'))

    with op.batch_alter_table('service_time', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_time_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_time_date_recorded'))

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_reminder_datetime'))

    with op.batch_alter_table('query_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_request_status'))
        batch_op.drop_index(batch_op.f('ix_query_request_created_at'))

    with op.batch_alter_table('guia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guia_titulo'))
        batch_op.drop_index(batch_op.f('ix_guia_created_at'))

    with op.batch_alter_table('duvida', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('discord_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_discord_ticket_created_at'))

    with op.batch_alter_table('comportamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comportamento_titulo'))
        batch_op.drop_index(batch_op.f('ix_comportamento_created_at'))
        batch_op.drop_index(batch_op.f('ix_comportamento_categoria'))

    # ### end Alembic commands ###
