"""Adiciona status de notificação aos lembretes

Revision ID: 6e44965096e5
Revises: 166fcc0a6c2a
Create Date: 2025-10-15 12:52:36.333443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e44965096e5'
down_revision = '166fcc0a6c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('notification_status')

    # ### end Alembic commands ###
