"""Tentativa 2 Adiciona Duvida e Resposta

Revision ID: 8d9fa258f186
Revises: f6c13ef96c18
Create Date: 2025-10-29 16:07:34.530165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9fa258f186'
down_revision = 'f6c13ef96c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duvida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('discord_message_id', sa.String(length=50), nullable=True),
    sa.Column('discord_thread_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duvida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duvida_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_duvida_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_duvida_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_duvida_titulo'), ['titulo'], unique=False)

    op.create_table('resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_discord_id', sa.String(length=50), nullable=True),
    sa.Column('duvida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['duvida_id'], ['duvida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('base', sa.VARCHAR(length=50), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=300), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('column_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['column.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_card_creator_id')),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resposta')
    with op.batch_alter_table('duvida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duvida_titulo'))
        batch_op.drop_index(batch_op.f('ix_duvida_status'))
        batch_op.drop_index(batch_op.f('ix_duvida_created_at'))
        batch_op.drop_index(batch_op.f('ix_duvida_categoria'))

    op.drop_table('duvida')
    # ### end Alembic commands ###
