"""Adiciona creator_id ao Card

Revision ID: f6c13ef96c18
Revises: 6e44965096e5
Create Date: 2025-10-17 11:58:33.641818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c13ef96c18'
down_revision = '6e44965096e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        # CORREÇÃO APLICADA AQUI
        batch_op.create_foreign_key('fk_card_creator_id', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        # CORREÇÃO APLICADA AQUI
        batch_op.drop_constraint('fk_card_creator_id', type_='foreignkey')
        batch_op.drop_column('creator_id')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
